config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boots_products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boots_product.rb
class BootsProduct < ApplicationRecord
end

app/models/preference.rb
class Preference < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boots_products_controller.rb
class BootsProductsController < ApplicationController
  before_action :set_boots_product, only: [:show, :edit, :update, :destroy]

  # GET /boots_products
  # GET /boots_products.json
  def index
    @boots_products = BootsProduct.all
  end

  # GET /boots_products/1
  # GET /boots_products/1.json
  def show
  end

  # GET /boots_products/new
  def new
    @boots_product = BootsProduct.new
  end

  # GET /boots_products/1/edit
  def edit
  end

  # POST /boots_products
  # POST /boots_products.json
  def create
    @boots_product = BootsProduct.new(boots_product_params)

    respond_to do |format|
      if @boots_product.save
        format.html { redirect_to @boots_product, notice: 'Boots product was successfully created.' }
        format.json { render :show, status: :created, location: @boots_product }
      else
        format.html { render :new }
        format.json { render json: @boots_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boots_products/1
  # PATCH/PUT /boots_products/1.json
  def update
    respond_to do |format|
      if @boots_product.update(boots_product_params)
        format.html { redirect_to @boots_product, notice: 'Boots product was successfully updated.' }
        format.json { render :show, status: :ok, location: @boots_product }
      else
        format.html { render :edit }
        format.json { render json: @boots_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boots_products/1
  # DELETE /boots_products/1.json
  def destroy
    @boots_product.destroy
    respond_to do |format|
      format.html { redirect_to boots_products_url, notice: 'Boots product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boots_product
      @boots_product = BootsProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boots_product_params
      params.fetch(:boots_product, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boots_products_helper.rb
module BootsProductsHelper

  def get_rate
    rate_str = Preference.where(key: 'gbp_to_cny_rate').first.value
    rate_str.to_f
  end

end

app/helpers/crawler_helper.rb
module CrawlerHelper

  @agent = Mechanize.new
  # @agent.user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'

  def self.get_appletuan_list(page: nil)
    url = 'http://www.appletuan.com/go/dailyprice'
    url += "?p=#{page}" unless page.nil?
    @agent.get url
  end

  def self.get_appletuan_topic(uri)
    @agent.get 'http://www.appletuan.com/' + uri
  end

  def self.get_price_history(url)
    @agent.get 'http://tool.manmanbuy.com/history.aspx?w=950&h=580&h2=360&m=1&e=1&tofanli=1&url=' + url
  end

  def self.get_boots_item(url)
    @agent.get url
  end

end

app/helpers/string_helper.rb
module StringHelper

  def self.match_first(regex, str)
    m = regex.match str
    return m ? m[1] : m
  end

end

app/views/boots_products/_form.html.erb
<%= form_for(boots_product) do |f| %>
  <% if boots_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boots_product.errors.count, "error") %> prohibited this boots_product from being saved:</h2>

      <ul>
      <% boots_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boots_products/edit.html.erb
<h1>Editing Boots Product</h1>

<%= render 'form', boots_product: @boots_product %>

<%= link_to 'Show', @boots_product %> |
<%= link_to 'Back', boots_products_path %>

app/views/boots_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boots 产品列表</h1>

<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">产品列表</div>
  <div class="weui-panel__bd">
    <% @boots_products.each do |boots_product| %>
    <a href="<%= url_for boots_product %>" class="weui-media-box weui-media-box_appmsg">
      <div class="weui-media__hd">
        <img class="weui-media__thumb" src="<%= boots_product.image_url %>" alt="">
      </div>
      <div class="weui-media__bd">
        <h4 class="weui-media__title"><%= boots_product.name %></h4>
        <p class="weui-media__desc">价格：￥<%= '%.2f' % ((boots_product.fixed_price || boots_product.price) * get_rate)
        %></p>
      </div>
    </a>
    <% end %>
  </div>
  <!--<div class="weui-panel__ft">-->
    <!--<a href="javascript:void(0);" class="weui-cell weui-cell_access weui-cell_link">-->
      <!--<div class="weui-cell__bd">查看更多</div>-->
      <!--<span class="weui-cell__ft"></span>-->
    <!--</a>-->
  <!--</div>-->
</div>

app/views/boots_products/new.html.erb
<h1>New Boots Product</h1>

<%= render 'form', boots_product: @boots_product %>

<%= link_to 'Back', boots_products_path %>

app/views/boots_products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_boots_product_path(@boots_product) %> |
<%= link_to 'Back', boots_products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
  <head>
    <title>Michael and Phoebe's Store</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" media="all" href="//cdnjs.cloudflare.com/ajax/libs/weui/1.0.0/style/weui.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>